# -*- coding: utf-8 -*-
"""Assignment 1_(Hackerrank)_ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o6vG7GvTmScj04rFXgdNlUW40xu3EiJo
"""

######## Question-1 ######

if __name__ == '__main__':
  n = int(input())
  student_marks = {}
  for _ in range(n):
    name, *line = input().split()
    scores =list(map(float,line))
    student_marks[name] = scores
  query_name = input()
print("%.02f"%(sum(student_marks[query_name]) /3))

###### Question-2 ######
def split_and_join(line):
  return '-'.join(line.split(' '))
if __name__ == '__main__':
  line = input()
  result = split_and_join(line)
  print(result)

########## Question-3 ##########
n = int(input())
a = set(map(int,input().split()))
m = int(input())
b = set(map(int,input().split()))
x =a.intersection(b)
print(len(x))

######### Question-4 #######
if __name__ == '__main__':
  n = int(input())
  arr = map(int, input().split())
  my_set = set(arr)
my_list = list (my_set)
my_list.sort()
print(my_list[-2])

########### Question-5 ##########
def swap_case(s):
    result = []
    for char in s:
        if char.isupper():
            result.append(char.lower())
        else:
            result.append(char.upper())
    return "".join(result)

if __name__ == '__main__':
  s= input()
  result= swap_case(s)
  print(result)

########### Question-6 ##########
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    
    print(a+b)
    print(a-b)
    print(a*b)

########## Question-7 ##########
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a/b)
    print(a//b)

########## Question-8 ##########
if __name__ == '__main__':
    n = int(input().strip())
if 1 <= n <= 100:
    if n % 2 == 0 and (n in range(2, 6) or n > 20):
        print('Not Weird')
    else:
        print('Weird')

########### Question-9 ##########
Result =[]
scorelist = []
if __name__ == '__main__':
    for _ in range(int(input())):
        name = input()
        score = float(input())
        Result+=[[name,score]]
        scorelist+=[score]
    b=sorted(list(set(scorelist)))[1] 
    for a,c in sorted(Result):
        if c==b:
            print(a)

########### Question-10 ##########

if __name__ == '__main__':
    n = int(input())
    
    for i in range(n):
        print(i**2)

########### Question-11 ##########
def is_leap(year):
    leap = False
    # Write your logic here
    if year > 1900:
        if year % 4 == 0:
            if year % 100 == 0:
                if year % 400 == 0:
                    leap = True;
                else:
                  leap= False
            else:
                leap= True
        else:
          leap= False
    return leap

year = int(input())
print(is_leap(year))

########### Question-12 ##########
def count_substring(string, sub_string):
    occurs = 0
    x = 0
    for i in range(len(string)):
        x = string.find(sub_string, x, len(string))
        if x >= 0:
            occurs += 1
            x += 1
    return occurs
if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

########### Question-13 ##########
if __name__ == '__main__':
    N = int(input())
    lst = []
    for _ in range(N):
    
        instruction = input().split()
        if instruction[0] == 'insert':
            lst.insert(int(instruction[1]), int(instruction[2]))
                
        elif instruction[0] == 'print':
            print(lst)
         
        elif instruction[0] == 'remove':
            # print(instruction)
            # print(lst)
            lst.remove(int(instruction[1]))
        
        elif instruction[0] == 'append':
            lst.append(int(instruction[1]))
            
        elif instruction[0] == 'sort':
            lst.sort()
            
        elif instruction[0] == 'pop':
            lst.pop()
            
        elif instruction[0] == 'reverse':
            lst.reverse()
        print(lst)

